server:
  port: 8002
  context-path:
  session:
    cookie:
      max-age: 30
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: YEKDBTEST
    password: test123456
    url: jdbc:mysql://192.168.80.174:3306/jeeplus_schema?useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

interfaceUrl: http://10.3.1.52:8001/yek_api/send.ashx?sign=y781821fa56a7698td
groupbuyPagecode: 4
cardtype: 积分卡
aboutusPagecode: 2
classroomPagecode: 3
privilegePagecode: 1

#logconfig
logging:
  file: c:/sportslog/sprots.log

#http:
#  maxTotal: 100
#  defaultMaxPerRoute: 20
#  connectTimeout: 1000
#  connectionRequestTimeout: 500
#  socketTimeout: 10000
#  staleConnectionCheckEnabled: true

